{% set name = "pydp" %}
{% set version = "0.1.2dev" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenMined/PyDP/archive/v{{ version }}.tar.gz
  sha256: de9fa4a4d731b1723944bab29cd323a54454c5492b122beff7ec8ae2e515d55f

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [win]

requirements:
  build:
    - bazel
  host:
    - python
    - pip
    - pytest
  run:
    - python
    - pytest

test:
  imports:
    - pydp
    - pydp.pydp

about:
  home: https://github.com/OpenMined/PyDP
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A python wrapper for https://github.com/google/differential-privacy"
  dev_url: https://github.com/OpenMined/PyDP

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
