{% set name = "python-dp" %}
{% set version = "0.1.7dev" %}
{% set commit = "1b1dc6639173c0a13613189ec21851604a4c7335" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/OpenMined/PyDP/archive/v{{ version }}.tar.gz
    sha256: 719e5a424bc60862d264ea4e712e9f74699b127b06910be6e6b70b4abd5c4147

  - url: https://github.com/google/differential-privacy/archive/{{ commit }}.tar.gz
    sha256: 03a3c53be6be5dbd05addd2c27ce997aba8635ee89376f7618d01ee628fb6690
    fn: differential-privacy.tar.gz
    folder: third_party/differential-privacy

  - url: https://github.com/python/cpython/archive/v3.5.9.tar.gz  # [py==35]
    sha256: 92ccdf1b133289c17bca40cc0539059af6444f7ed7044767e126f4b737325b5b  # [py==35]
    fn: python3.5.tar.gz  # [py==35]
    folder: pylib/python35  # [py==35]

  - url: https://github.com/python/cpython/archive/v3.6.12.tar.gz  # [py==36]
    sha256: ff5103d4c6ddf47428e80f8f937f6f3eddfae56bf43bcf20dbd67bb7e0b5075c  # [py==36]
    fn: python3.6.tar.gz  # [py==36]
    folder: pylib/python36  # [py==36]

  - url: https://github.com/python/cpython/archive/v3.7.9.tar.gz  # [py==37]
    sha256: 4763246f97cfe4a9d45b6909c4c52d5123d536666d98be4200f5327cf20032fa  # [py==37]
    fn: python3.7.tar.gz  # [py==37]
    folder: pylib/python37  # [py==37]

  - url: https://github.com/python/cpython/archive/v3.8.5.tar.gz  # [py==38]
    sha256: ebac44a9393c034b8e5c8387675ead5bb5b15770f78076e4376cb603864f700e  # [py==38]
    fn: python3.8.tar.gz  # [py==38]
    folder: pylib/python38  # [py==38]

build:
  number: 0
  skip: True  # [win or py<35]

requirements:
  build:
    - {{ compiler('cxx') }}
    - bazel ==2.1.0
  host:
    - python
    - pip
    - pytest
  run:
    - python
    - pytest

test:
  source_files:
    - tests
  imports:
    - pydp
  commands:
    - pytest tests

about:
  home: https://github.com/OpenMined/PyDP
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A python wrapper for https://github.com/google/differential-privacy"
  dev_url: https://github.com/OpenMined/PyDP

extra:
  recipe-maintainers:
    - alejandrosame
